language: node_js
node_js:
  - "10"
before_install:
  - npm install
  - npm install -g mocha
  - npm install -g chai 
  - npm install -g chai-http
  - export NODE_ENV=production
script:
  - npm run test